### ISSUE TITLE
`sh:class` of `sh:qualifiedValueShape [ sh:class ]`

### ISSUE THREAD

**Issue by redmer** [nl-digigo/nen2660#2]
https://github.com/bimloket/nen2660/blob/c068f6787f3439f1d2612765263e2d8ef7af3e87/data/nen2660-shacl.ttl#L80-L83

In NEN 2660 wordt `sh:class` gebruikt om voor o.a. `nen2660:hasPart` aan te geven, welke klasse verwacht wordt bij de waarde ervan. Bijvoorbeeld in bovenstaand voorbeeld bij `nen2660:ConcreteConcept`.

Bij IMBOR merken we dat extra beperkingen, niet goed opgepikt worden. Wellicht omdat de IMBOR-beperkingen met `:Boom nen2660:qualifiedValueShape [ sh:class :Armatuur ]` definieert. Dit na aanleiding na feedback Stichting-CROW/imbor#626.

Het probleem is dat dat `:Boom1 nen2660:hasPart :Armatuur1` niet valideert in SHACL; wellicht omdat `:Armatuur1` wel `:Armatuur` is, maar niet alleen maar `:Object`. 

Is dit hetzelfde probleem, @WouterLubbers? /cc @MichelBohms

**Comment by MichelBohms** [comment]
nen2660:qualifiedValueShape

???
Die kenne we niet in 2660

Wellicht sh:

**Comment by RiX012** [comment]
> nen2660:qualifiedValueShape ??? Die kenne we niet in 2660 Wellicht sh:

Ja typo. Inderdaad sh:qualifiedValueShape

**Comment by MichelBohms** [comment]
Wat beoogd men met:

:Boom sh:qualifiedValueShape [ sh:class :Armatuur ] definieert.


Is dat niet gewoon semantisch incorrect?
Welke praktische situatie wordt hiermee gemodelleerd?

**Comment by RiX012** [comment]
> Wat beoogd men met: :Boom sh:qualifiedValueShape [ sh:class :Armatuur ] definieert. Is dat niet gewoon semantisch incorrect? Welke praktische situatie wordt hiermee gemodelleerd?

Of het semantisch correct is laat ik graag aan de IMBOR werkgroep Bomen. Maar men wil aangeven dat er 0:1 Armatuur onderdeel van een Boom kan zijn. 

De fout in de validatie geldt onafhankelijk van de semantiek.

**Comment by RiX012** [comment]
@MichelBohms heb je hier nog over na kunnen denken? Wij lopen hier ws niet als enige tegen aan.

> > Wat beoogd men met: :Boom sh:qualifiedValueShape [ sh:class :Armatuur ] definieert. Is dat niet gewoon semantisch incorrect? Welke praktische situatie wordt hiermee gemodelleerd?
> 
> Of het semantisch correct is laat ik graag aan de IMBOR werkgroep Bomen. Maar men wil aangeven dat er 0:1 Armatuur onderdeel van een Boom kan zijn.
> 
> De fout in de validatie geldt onafhankelijk van de semantiek.

**Comment by MichelBohms** [comment]
Vgl vb uit spec:

ex:QualifiedValueShapeExampleShape
         a sh:NodeShape ;
         sh:targetNode ex:QualifiedValueShapeExampleValidResource ;
         sh:property [
                 sh:path ex:parent ;
                 sh:minCount 2 ;
                 sh:maxCount 2 ;
                 sh:qualifiedValueShape [
                          sh:path ex:gender ;
                          sh:hasValue ex:female ;
                 ] ;
                 sh:qualifiedMinCount 1 ;
         ] .
Optioneel onderdeel wordt dan denk ik:

ex:QualifiedValueShapeBoomShape
                a sh:NodeShape ;
                sh:targetNode ex:Boom ;
                sh:property [
                               sh:path nen2660:hasPart ;
                               sh:qualifiedValueShape [
                                               sh:class ex:Armatuur
                               ] ;
                               sh:qualifiedMaxCount 1 ;
                ] .

Is dat nu anders gemodelleerd?

**Comment by RiX012** [comment]
Nee we doen hetzelfde

De shapes zijn: 

imbor:Boom a rdf:Class, sh:NodeShape ;
   sh:property 		imbor:BoomShape .

imbor:BoomShape a sh:PropertyShape ;
		sh:path 		nen2660:hasPart;
		sh:qualifiedMaxCount	 1;
		sh:qualifiedValueShape	[	sh:class  	imbor:Armatuur ] .

De data set is:

ex:Boom1 	a imbor:Boom
		nen2660:hasPart	ex:Armatuur1
ex:Armatuur1	a imbor:Armatuur



Het validatie rapport geeft dan aan:

sh:result    [ rdf:type                      sh:ValidationResult ;
                 sh:focusNode                  ex:Boom1 ;
                 sh:resultMessage              "Value must be an instance of _:a3c3a4edbb04db3a4be6c5da325664e6" ;
                 sh:resultPath                 nen2660:hasPart ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:ClassConstraintComponent ;
                 sh:sourceShape                []  ;
                 sh:value                      ex:Armatuur1
               ] ;

**Comment by WouterLubbers** [comment]
Een combinatie van directe sh:class constraints (vanuit NEN 2660) en sh:qualifiedValueShape constraints (IMBOR) zou gewoon moeten kunnen. De foutmelding die uit de SHACL validator komt snap ik niet, aangezien hier een instantie van een bepaalde blank node gevraagd wordt (_:a3c3a4edbb04db3a4be6c5da325664e6). Dit staat in de bovenstaande shapes nergens benoemd. Ik vermoed daarom dat deze validatiefout door een andere shape veroorzaakt wordt (misschien in een bovenliggende klasse?).

Ik krijg op basis van vergelijkbare testdata ook andere resultaten. In het voorbeeld is alleen 'Wheel' als onderdeel gedefinieerd, maar ook instanties van 'Door' worden geaccepteerd als onderdeel.

Met deze shapesfile:
```@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix def:   <http://example.org/def/> .
@prefix nen2660: <https://w3id.org/nen2660/def#> .

def: a owl:Ontology .

nen2660:hasPart
  a owl:ObjectProperty ;
.

nen2660:RealObject
  a sh:NodeShape, owl:Class ;
  sh:property [
      sh:path nen2660:hasPart ;
	  sh:class nen2660:RealObject 
    ] ;
.

def:Car
        rdf:type            sh:NodeShape , owl:Class ;
		rdfs:subClassOf		nen2660:RealObject ;
		sh:property  [ sh:path  nen2660:hasPart ;
						sh:qualifiedMinCount 1 ;
						sh:qualifiedMaxCount 1 ;
						sh:qualifiedValueShape [ sh:class def:Wheel ] ;
						] ;
.

def:Wheel
        rdf:type            sh:NodeShape , owl:Class .

def:Door
        rdf:type            sh:NodeShape , owl:Class .
```

En deze instanties:
```@prefix :      <http://www.example.org/id/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix def:   <http://example.org/def/> .
@prefix nen2660: <https://w3id.org/nen2660/def#> .

: a owl:Ontology .

:Car_1 rdf:type def:Car ;
	nen2660:hasPart :Wheel_1 ;
#	nen2660:hasPart :Wheel_2 ;
	nen2660:hasPart :Door_1 ;
.
	
:Wheel_1 rdf:type def:Wheel .

:Wheel_2 rdf:type def:Wheel .

:Door_1 rdf:type def:Door .
```

**Comment by MichelBohms** [comment]
Idd in spec:

***@***.***

Maar dit is de hoofdlijn: onder die node/property shape kunnen alle details vallen van shacl.

Is data hieronder gecheckt met TQ TBC?

(dan kunnen we deze false negatives/positives eens voorleggen aan TQ-list)…

Vg michel

**Comment by redmer** [comment]
@RiX012 en ik hebben het wellicht gevonden: in https://github.com/bimloket/nen2660/blob/gh-pages/data/nen2660-shacl.ttl#L261-L265 en in https://github.com/bimloket/nen2660/blob/gh-pages/data/nen2660-shacl.ttl#L313-L317 wordt de `sh:class`-waarde een `owl:unionOf`. Naar mijn inzicht is dat niet te interpreteren door een SHACL-systeem.

**Comment by WouterLubbers** [comment]
Waarschijnlijk wel, het verklaart in ieder geval waarom een blank node verwacht wordt. Binnen SHACL zou dit met een [logical constraint](https://www.w3.org/TR/shacl/#core-components-logical) opgelost moeten worden, in deze gevallen sh:or of sh:xone.

**Comment by MichelBohms** [comment]
Blijft:

Geen error bij

@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .
@prefix sh: http://www.w3.org/ns/shacl# .
@prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix ex: http://example.org/def/ .
@prefix owl: http://www.w3.org/2002/07/owl# .

ex: a owl:Ontology .

ex:hasPart
  a owl:ObjectProperty .

ex:RealObject
  a sh:NodeShape, owl:Class ;
  sh:property [
      sh:path ex:hasPart ;
                sh:class ex:RealObject
    ] ; .

ex:Car
  a sh:NodeShape, owl:Class ;
  rdfs:subClassOf ex:RealObject ;
  sh:property  [sh:path  ex:hasPart ;
                            sh:qualifiedMinCount 1 ;
                            sh:qualifiedMaxCount 1 ;
                            sh:qualifiedValueShape [ sh:class ex:Wheel ] ;
    ] ; .

ex:Wheel
  a sh:NodeShape, owl:Class .

ex:Door
  a sh:NodeShape, owl:Class .

ex:hasPart
  a owl:ObjectProperty .

ex:Car_1 rdf:type ex:Car ;
              ex:hasPart ex:Wheel_1 ;
              ex:hasPart ex:Wheel_2 ;
              ex:hasPart ex:Door_1 .

ex:Wheel_1 rdf:type ex:Wheel .
ex:Wheel_2 rdf:type ex:Wheel .
ex:Door_1 rdf:type ex:Door .

toch?
Zal ik tq is vragen?



Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<https://nextdelft.com/>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

***@***.***

**Comment by RiX012** [comment]
> Waarschijnlijk wel, het verklaart in ieder geval waarom een blank node verwacht wordt. Binnen SHACL zou dit met een [logical constraint](https://www.w3.org/TR/shacl/#core-components-logical) opgelost moeten worden, in deze gevallen sh:or of sh:xone.

Dit is wel belangrijk om aan te passen in de source files. @MichelBohms kun jij dat doen?

> toch? Zal ik tq is vragen?

Klopt. Lijkt me verstandig. 

Als ik de bovengenaamde data van @WouterLubbers valideer tegen de bovengenoemde shapes, krijg ik met PySHACL:
`Validation Report`
`Conforms: True`
... en met de TopQuadrant SHACL API:
`rdf:type     sh:ValidationReport ;`
`  sh:conforms  false ;`
`  sh:result    [ rdf:type                      sh:ValidationResult ;`
  `               sh:focusNode                  id:Car_1 ;`
  `               sh:resultMessage              "More than 1 values have shape _:4682ad5abebd87c6371b12f3b82d5f6a" ;`
     `           sh:resultPath                 nen2660:hasPart ;`
   `             sh:resultSeverity             sh:Violation ;`
  `              sh:sourceConstraintComponent  sh:QualifiedMaxCountConstraintComponent ;`
 `                sh:sourceShape                []`
    `           ]`

**Comment by MichelBohms** [comment]
Huh, is dat een edit aan 2660 kant?



Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<https://nextdelft.com/>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

***@***.***

**Comment by MichelBohms** [comment]
Wat is nu precies onze verwachting bij:

ex:Car
  a sh:NodeShape, owl:Class ;
  rdfs:subClassOf ex:RealObject ;
  sh:property  [sh:path  ex:hasPart ;
                            sh:qualifiedMinCount 1 ;
                            sh:qualifiedMaxCount 1 ;
                            sh:qualifiedValueShape [ sh:class ex:Wheel ] ;
    ] ; .

ex:Car_1 rdf:type ex:Car ;
              ex:hasPart ex:Wheel_1 ;
              ex:hasPart ex:Wheel_2 ;
              ex:hasPart ex:Door_1 .

1 error of 2 errors?

Ik dacht: 1 error (2 ipv 1 wheel)
Door mag want daar is geen aparte property shape voor (zijnde maxcard=0 voor haspart door)

Of denk ik nou verkeerd?



Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<https://nextdelft.com/>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

***@***.***

**Comment by RiX012** [comment]
> Huh, is dat een edit aan 2660 kant?

Ja in deze lines:
>@RiX012 en ik hebben het wellicht gevonden: in https://github.com/bimloket/nen2660/blob/gh-pages/data/nen2660-shacl.ttl#L261-L265 en in https://github.com/bimloket/nen2660/blob/gh-pages/data/nen2660-shacl.ttl#L313-L317 wordt de sh:class-waarde een owl:unionOf. Naar mijn inzicht is dat niet te interpreteren door een SHACL-systeem.

Dat zou dus niet met OWLmoeten, maar met SHACL

**Comment by MichelBohms** [comment]
nen2660:RealObject
  a sh:NodeShape ;
  sh:property [
      sh:path nen2660:consistsOf ;
      sh:or ( [ sh:class nen2660:Matter] [sh:class nen2660:MatterPortion ] ) ;
    ] ;
  sh:property [
      sh:path nen2660:hasPart ;
      sh:class [
          a owl:Class ;
          owl:unionOf (
              nen2660:RealObject
              nen2660:Port
            ) ;
        ] ;
    ] ;
.
die 2e propertyshape moet dus ook ala die eerste…
Right?

michel




Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<https://nextdelft.com/>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

***@***.***

**Comment by MichelBohms** [comment]
Idd!
Ga ik iig in code wijzigen.

Misschien nog in doc…

Blijft staan de anedre vraag (verwachte uitkomst)




Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<https://nextdelft.com/>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

***@***.***

**Comment by RiX012** [comment]
> die 2e propertyshape moet dus ook ala die eerste… Right?

Klopt. Heb het net handmatig aangepast en getest.

**Comment by RiX012** [comment]
> Idd! Ga ik iig in code wijzigen. Misschien nog in doc… Blijft staan de anedre vraag (verwachte uitkomst)

Top.
Andere vraag staat inderdaad nog open. @WouterLubbers zou het het beste kunnen aangegeven. Ik ben ook ff lost.

**Comment by WouterLubbers** [comment]
Eens met de aanpassing in de NEN2660 code.

Voor de verwachte uitkomst:
- Door_1 als part is inderdaad toegestaan: door gebruik van qualifiedValueShape zijn andere parts niet uitgesloten. De enige verwachte foutmelding zou dus moeten zijn dat er een instantie van Wheel te veel is (max 1).
- Als de constraint op RealObject correct volgens SHACL gemodelleerd is (en RealObject als onderdeel alleen een Port of een RealObject mag hebben), zou ik ook een foutmelding verwachten dat zowel Wheel als Door in dit voorbeeld niet een specialisatie van RealObject of Port zijn. Car is namelijk wel een specialisatie van RealObject.

**Comment by MichelBohms** [comment]
Helemaal helder en mee eens.

Misschien is er in tbc wel eerst inference nodig! Om die car > realobject af te leiden! En dan die 2e fout te geven.
Hmmm eerst maar eens die eerste.
Staat uit bij tq list.

Op 14 jun. 2022 19:01 schreef WouterLubbers ***@***.***>:

Eens met de aanpassing in de NEN2660 code.

Voor de verwachte uitkomst:

  *   Door_1 als part is inderdaad toegestaan: door gebruik van qualifiedValueShape zijn andere parts niet uitgesloten. De enige verwachte foutmelding zou dus moeten zijn dat er een instantie van Wheel te veel is (max 1).
  *   Als de constraint op RealObject correct volgens SHACL gemodelleerd is (en RealObject als onderdeel alleen een Port of een RealObject mag hebben), zou ik ook een foutmelding verwachten dat zowel Wheel als Door in dit voorbeeld niet een specialisatie van RealObject of Port zijn. Car is namelijk wel een specialisatie van RealObject.

**Comment by MichelBohms** [comment]
Deze testfile gaat nu goed in TBC (ik zal nog testen met extern RealObject en extra constraints)
***@***.***


@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .
@prefix sh: http://www.w3.org/ns/shacl# .
@prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix ex: http://example.org/def/ .
@prefix owl: http://www.w3.org/2002/07/owl# .

ex: a owl:Ontology ;
  owl:imports http://www.w3.org/ns/shacl .

ex:hasPart
  a owl:ObjectProperty .

ex:RealObject
  a sh:NodeShape, owl:Class ;
  sh:property [
      sh:path ex:hasPart ;
                sh:class ex:RealObject
    ] ; .

ex:Car
  a sh:NodeShape, owl:Class ;
  rdfs:subClassOf ex:RealObject ;
  sh:property  [sh:path  ex:hasPart ;
                            sh:qualifiedMinCount 1 ;
                            sh:qualifiedMaxCount 1 ;
                            sh:qualifiedValueShape [ sh:class ex:Wheel ] ;
    ] ; .

ex:Wheel
  a sh:NodeShape, owl:Class .

ex:Door
  a sh:NodeShape, owl:Class .

ex:hasPart
  a owl:ObjectProperty .

ex:Car_1 rdf:type ex:Car ;
              ex:hasPart ex:Wheel_1 ;
              ex:hasPart ex:Wheel_2 ;
              ex:hasPart ex:Door_1 .

ex:Wheel_1 rdf:type ex:Wheel .
ex:Wheel_2 rdf:type ex:Wheel .
ex:Door_1 rdf:type ex:Door .

**Comment by RiX012** [comment]
Ja ik denk dat we er inderdaad uit zijn. Ik ondervindt zelf nog wat ingewikkeldheden met inferencing. Ik kan geen optie bij de TBQ SHACL API vinden om inferencing eerst te doen. Maar verder gaat de validatie nu goed.

**Comment by MichelBohms** [comment]
Alle shacl lijkt nu ok

Iig voor: test2

**Comment by redmer** [comment]
Verwerkt met de wijzigingen in https://github.com/bimloket/nen2660/commit/c6b7dd1f44cd108326feac86d0dfdb3b604336d3#diff-6904c7e9b019e9a307915930a95359a19a96323ca8c3bc5a02d479b2c1f39375

**Comment by MichelBohms** [comment]
Hoi Rik

Sorry help ff mn geheugen…

Is het issue nu:

Validatie (In tbc?) geeft onterechte fout of iets anders (bv syntactische correctheid)

Thx michel

**Comment by MichelBohms** [comment]
Misschien kun je nog s naar mn laatste mail naar tq kijken (test2)

Of ik niks over het hoofd zie…..

Meestal is Holger niet blij als ik een triviale fout maak en hem voorleg 😊

**Comment by RiX012** [comment]
Wat mij betreft is dit issue resolved hoor!
