### ISSUE TITLE
In TTL files staat 'Aktiviteit' ipv 'Activiteit'

### ISSUE THREAD

**Issue by RiX012** [nl-digigo/nen2660#4]
@MichelBohms Minor issue, maar geen goed NL

**Comment by redmer** [comment]
Om precies te zijn op: https://github.com/bimloket/nen2660/blob/c068f6787f3439f1d2612765263e2d8ef7af3e87/data/nen2660-skos.ttl#L46-L47

**Comment by MichelBohms** [comment]
Aangepast in code file skos
Pas jij het online aan?

**Comment by redmer** [comment]
Verwerkt in feb4746
